language: python

python:
  - "3.5"

services:
  - mysql

env:
  - SECRET_KEY=secret DB=mysql

install:
  - pip install -r requirements.txt

before_script:
  - mysql -e 'create database test;' -u root

script:
  - python manage.py test

branches:
  only:
  - develop