language: python

python:
  - "3.5"

services:
  - mysql

env:
  - SECRET_KEY=secret
  - DATABASE_HOST=127.0.0.1
  - DATABASE_PORT=3306
  - DATABASE_NAME=test
  - DATABASE_USER=root

install:
  - pip install -r requirements.txt

before_script:
  - mysql -e 'create database test;' -u root

script:
  - python manage.py test

branches:
  only:
  - develop